### ISSUE TITLE
Device does no longer successfully uninstall in version v.1.11.0

### ISSUE THREAD

**Issue by timminator** [nefarius/nefcon#19] opened 2024-11-02 15:41 UTC
Hi!
First off all thank you for this amazing project!
I've ran into an issue using your latest release version v1.11.0
I'm using your project to install the Virtual Display Driver by MikeTheTech via the command line (https://github.com/timminator/Virtual-Display-Driver).
But I also noticed you left me a star so you seem to be aware of my project. :-)
I came in contact with the team behind the main repo and I was working on updating my installer for the newest display driver version.
While doing that I wanted to update the used nefcon version from v1.10.0 to the latest version v1.11.0 aswell.

But using the latest version the driver does no longer successfully uninstall. This worked perfectly fine using nefcon version v1.10.0.

Im using the following commands to install and uninstall the legacy hardware device:

Installation:
- ...\nefconw.exe --create-device-node --hardware-id Root\HidHide --class-name Display --class-guid ...
- ...\nefconw.exe --install-driver --inf-path "Path\To\Inf.inf"

Uninstall:
- ...\nefconw.exe --remove-device-node --hardware-id Root\HidHide --class-guid ...

I've also swapped nefconw with nefconc in the hope that there may be a helpful output in the command line but the command ran through without printing anything. The device is still showing up in device manager after running the command with version v1.11.0 whereas in version v1.10.0 it was successfully removed.

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read [the project documentation](https://docs.nefarius.at/projects/) and not found a solution to my problem there
- [x] This isn't a feature request or a discussion topic

### Steps to reproduce

I've only tested it using my installer, but it should be something like:
- Download latest vdd release from itsmikethetech [here](https://github.com/itsmikethetech/Virtual-Display-Driver/releases/tag/23.12.2HDR)
- Copy them to C:\IddSampleDriver and run the *.bat file to install the certificate
- Run the commands I posted above

**Actual result:** Device still installed (v1.11.0)
**Expected result:** Device successfully uninstalled

### Machine info

CPU-Architecture: x64
Windows version: Windows 11 Home 24H2
**Software/driver version(s):** 1.11.0

**Comment by nefarius** [comment] 2024-11-02 16:01
Hey there!

nefcon has verbose logging flags, please use those when testing both versions and for each case also provide the file `C:\Windows\INF\setupapi.dev.log` here, thanks.

**Comment by timminator** [comment] 2024-11-02 16:48
Thank you for your quick response.
The results are very weird, in version v1.11.0 I got only one message and zero output in the setupapi.dev.log file.
In version v.1.10.0 the logs seems correct.

v.1.11.0:
log.txt:
2024-11-02 17:25:59,503 VERBOSE-1 [default] Invoked --remove-device-node
setapi.dev.log:
-empty


v.1.10.0:
log.txt:
2024-11-02 17:27:48,575 VERBOSE-1 [default] Invoked --remove-device-node
2024-11-02 17:27:48,579 VERBOSE-1 [default] SetupDiEnumDeviceInfo with index 0
2024-11-02 17:27:48,581 VERBOSE-1 [default] (Re-)allocating property buffer, bytes: 34
2024-11-02 17:27:48,581 VERBOSE-1 [default] Got Hardware ID property, starting enumeration
2024-11-02 17:27:48,581 VERBOSE-1 [default] Enumerating ID: Root\Parsec\VDA
2024-11-02 17:27:48,581 VERBOSE-1 [default] Done enumerating Hardware IDs
2024-11-02 17:27:48,581 VERBOSE-1 [default] SetupDiEnumDeviceInfo with index 1
2024-11-02 17:27:48,581 VERBOSE-1 [default] (Re-)allocating property buffer, bytes: 292
2024-11-02 17:27:48,581 VERBOSE-1 [default] Got Hardware ID property, starting enumeration
2024-11-02 17:27:48,599 VERBOSE-1 [default] Enumerating ID: PCI\VEN_1002&DEV_1636&SUBSYS_876E103C&REV_C3
2024-11-02 17:27:48,599 VERBOSE-1 [default] Enumerating ID: CI\VEN_1002&DEV_1636&SUBSYS_876E103C
2024-11-02 17:27:48,599 VERBOSE-1 [default] Enumerating ID: CI\VEN_1002&DEV_1636&CC_030000
2024-11-02 17:27:48,599 VERBOSE-1 [default] Enumerating ID: CI\VEN_1002&DEV_1636&CC_0300
2024-11-02 17:27:48,599 VERBOSE-1 [default] Done enumerating Hardware IDs
2024-11-02 17:27:48,599 VERBOSE-1 [default] SetupDiEnumDeviceInfo with index 2
2024-11-02 17:27:48,599 VERBOSE-1 [default] (Re-)allocating property buffer, bytes: 44
2024-11-02 17:27:48,599 VERBOSE-1 [default] Got Hardware ID property, starting enumeration
2024-11-02 17:27:48,599 VERBOSE-1 [default] Enumerating ID: ROOT\iddsampledriver
2024-11-02 17:27:48,599 VERBOSE-1 [default] Found match against ROOT\iddsampledriver, attempting removal
2024-11-02 17:27:48,604 VERBOSE-1 [default] Enumerating
2024-11-02 17:27:50,312 VERBOSE-1 [default] Reboot required: 0
2024-11-02 17:27:50,313 VERBOSE-1 [default] Freed memory, returning with 1 and error code 0
2024-11-02 17:27:50,313 VERBOSE-1 [default] Removal response: 1, error code: 0
2024-11-02 17:27:50,313 VERBOSE-1 [default] Done enumerating Hardware IDs
2024-11-02 17:27:50,314 VERBOSE-1 [default] Freed memory and returning with status: 1
2024-11-02 17:27:50,314 INFO [default] Device and driver removed successfully

setapi.dev.log:
>>>  [Driver Uninstall (DiUninstallDriver) - C:\WINDOWS\INF\oem38.inf]
>>>  Section start 2024/11/02 17:27:49.862
      cmd: C:\IddSampleDriver\nefconw.exe  --remove-device-node --hardware-id ROOT\iddsampledriver --class-guid 4d36e968-e325-11ce-bfc1-08002be10318 --default-log-file=.\log.txt --verbose
     ndv: Flags: 0x00000000
     ndv: INF path: C:\WINDOWS\INF\oem38.inf
     dvs: {DrvSetupUninstallDriver - C:\WINDOWS\INF\oem38.inf}
     dvs:      Flags: 0x00000000
     dvs:      {Driver Setup Delete Driver Package: oem38.inf} 17:27:50.033
     ump:           Delete flags: 0x00000002
     pol:           {Driver package policy check} 17:27:50.116
     pol:           {Driver package policy check - exit(0x00000000)} 17:27:50.118
     sto:           {Unstage Driver Package: C:\WINDOWS\System32\DriverStore\FileRepository\iddsampledriver.inf_amd64_2d1b8434bc8335a5\iddsampledriver.inf} 17:27:50.121
     inf:                Provider       = MikeTheTech
     inf:                Class GUID     = {4d36e968-e325-11ce-bfc1-08002be10318}
     inf:                Class Version  = 2.0
     inf:                Driver Version = 10/14/2023,10.26.6.91
     inf:                Catalog File   = IddSampleDriver.cat
     inf:                Version Flags  = 0x00000003
     sto:                {Core Driver Package Delete: iddsampledriver.inf_amd64_2d1b8434bc8335a5} 17:27:50.135
     sto:                     {DRIVERSTORE DELETE BEGIN} 17:27:50.137
     sto:                     {DRIVERSTORE DELETE BEGIN: exit(0x00000000)} 17:27:50.139
     sto:                     {Unconfigure Driver Package: C:\WINDOWS\System32\DriverStore\FileRepository\iddsampledriver.inf_amd64_2d1b8434bc8335a5\iddsampledriver.inf} 17:27:50.141
     inf:                          Config Options = IsolationCompat
     inf:                          Class GUID     = {4d36e968-e325-11ce-bfc1-08002be10318}
     inf:                          Class Options  = Configurable
     inf:                          {Unconfigure Driver: Virtual Display Driver by MTT}
     inf:                               Section Name = MyDevice_Install.NT
     inf:                               {Add Service: WUDFRd}
     inf:                                    Service 'WUDFRd' still in use by 14 sources.
     inf:                               {Add Service: exit(0x00000000)}
     inf:                               AddReg: HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\WUDF\Services\IddSampleDriver\WdfMajorVersion
     inf:                               AddReg: HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\WUDF\Services\IddSampleDriver\WdfMinorVersion
     inf:                               AddReg: HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\WUDF\Services\IddSampleDriver\ImagePath
     inf:                               AddReg: HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\WUDF\Services\IddSampleDriver\WdfExtensions
     inf:                               Hardware Id  = Root\IddSampleDriver
     inf:                          {Unconfigure Driver: exit(0x00000000)}
     flq:                          {FILE_QUEUE_COMMIT} 17:27:50.172
     flq:                               DeleteFile: 'C:\WINDOWS\System32\drivers\UMDF\IddSampleDriver.dll'
     flq:                               DeleteFile: 'C:\WINDOWS\System32\drivers\UMDF\IddSampleDriver.dll'
     flq:                               DeleteFile: success
     flq:                          {FILE_QUEUE_COMMIT - exit(0x00000000)} 17:27:50.189
     sto:                     {Unconfigure Driver Package: exit(0x00000000)} 17:27:50.191
     idb:                     {Unpublish Driver Package: C:\WINDOWS\System32\DriverStore\FileRepository\iddsampledriver.inf_amd64_2d1b8434bc8335a5\iddsampledriver.inf} 17:27:50.193
     idb:                          Clearing active driver package 'iddsampledriver.inf_amd64_2d1b8434bc8335a5'.
     cpy:                          Unpublished 'oem38.inf'.
     idb:                          Deindexed 2 device IDs for 'iddsampledriver.inf_amd64_2d1b8434bc8335a5'.
     sto:                          Flushed driver database node 'DRIVERS'. Time = 0 ms
     sto:                          Flushed driver database node 'SYSTEM'. Time = 0 ms
     idb:                     {Unpublish Driver Package: exit(0x00000000)} 17:27:50.213
     idb:                     {Unregister Driver Package: C:\WINDOWS\System32\DriverStore\FileRepository\iddsampledriver.inf_amd64_2d1b8434bc8335a5\iddsampledriver.inf} 17:27:50.217
     idb:                          Unregistered driver package 'iddsampledriver.inf_amd64_2d1b8434bc8335a5' from 'oem38.inf'.
     idb:                          Deleted driver package object 'iddsampledriver.inf_amd64_2d1b8434bc8335a5' from DRIVERS database node.
     idb:                          Deleted driver INF file object 'oem38.inf' from DRIVERS database node.
     idb:                     {Unregister Driver Package: exit(0x00000000)} 17:27:50.224
     cpy:                     {Delete Directory: C:\WINDOWS\System32\DriverStore\FileRepository\iddsampledriver.inf_amd64_2d1b8434bc8335a5} 17:27:50.226
     cpy:                     {Delete Directory: exit(0x00000000)} 17:27:50.229
     sto:                     {DRIVERSTORE DELETE END} 17:27:50.231
     sig:                          Uninstalled catalog 'oem38.cat'.
     sto:                     {DRIVERSTORE DELETE END: exit(0x00000000)} 17:27:50.243
     sto:                {Core Driver Package Delete: exit(0x00000000)} 17:27:50.245
     sto:           {Unstage Driver Package: exit(0x00000000)} 17:27:50.246
     dvs:      {Driver Setup Delete Driver Package - exit (0x00000000)} 17:27:50.272
     dvs: {DrvSetupUninstallDriver - exit(00000000)}
<<<  Section end 2024/11/02 17:27:50.312
<<<  [Exit status: SUCCESS]

**Comment by nefarius** [comment] 2024-11-02 18:10
Thanks. Hm, 1.10 to 1.11 I did a huge reactor, guess something went wrong with that command, gonna take a look at the sources and maybe throw back in some more logging.

**Comment by nefarius** [comment] 2024-11-02 18:18
Just tried it myself; looks like we have a good old-fashioned app crash on our hands:

![image](https://github.com/user-attachments/assets/53015cd4-203f-4639-a094-04c91d589892)

**Comment by nefarius** [comment] 2024-11-02 19:02
@timminator should be fixed, please build the branch in #20 and test, should work now as intended.

**Comment by nefarius** [comment] 2024-11-02 19:14
Alternatively here are the [binaries from CI](https://github.com/nefarius/nefcon/actions/runs/11645152042/artifacts/2136746509).

**Comment by timminator** [comment] 2024-11-03 11:54
Thank you for fixing the problem so quickly and for posting the new binaries.
Uninstalling the device does now work correctly.
Do you plan on creating a new release with this fix in place?

**Comment by nefarius** [comment] 2024-11-03 12:35
Yes, now that we both confirmed it working I'll merge it and make a new signed release probably later today.

**Closed** 2024-11-03 15:03 UTC
Labels: bug

**Comment by nefarius** [comment] 2024-11-03 16:54
Release published: https://github.com/nefarius/nefcon/releases/tag/v1.11.1

Thank you very much for reporting!
